site_name: My site
site_url: https://mydomain.org/mysite
theme:
  name: material
  language: zh
extra:
  alternate:
    - name: English
      link: /en/
      lang: en
    - name: 简体中文
      link: /
      lang: zh